# This is the configuration used to check the rubocop source code.

Rails:
  Enabled: true

Documentation:
  Enabled: false

  AllCops:
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*


LineLength:
  Max: 99

HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

# rubocop-rspec custom configurations

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ExampleLength:
  Exclude:

RSpec/AnyInstance:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 3
