development:
  mail:
    address: <%= ENV['MAILTRAP_ADDRESS_DEVELOPMENT'] %>
    domain: <%= ENV['MAILTRAP_DOMAIN_DEVELOPMENT'] %>
    port: <%= ENV['MAILTRAP_PORT_DEVELOPMENT'] %>
    username: <%= ENV['MAILTRAP_USERNAME_DEVELOPMENT'] %>
    password: <%= ENV['MAILTRAP_PASSWORD_DEVELOPMENT'] %>
  redis:
    url: <%= ENV['REDIS_URL'] %>
  open_library:
    url: <%= ENV['OPEN_LIBRARY_URL'] %>


production:
  mail:
    address: <%= ENV['MAILTRAP_ADDRESS'] %>
    domain: <%= ENV['MAILTRAP_DOMAIN'] %>
    port: <%= ENV['MAILTRAP_PORT'] %>
    username: <%= ENV['MAILTRAP_USERNAME'] %>
    password: <%= ENV['MAILTRAP_PASSWORD'] %>
  redis:
    url: <%= ENV['REDIS_URL'] %>
  open_library:
    url: <%= ENV['OPEN_LIBRARY_URL'] %>