development:
  mail:
    address: <%= ENV['MAILTRAP_ADDRESS_DEVELOPMENT'] %>
    domain: <%= ENV['MAILTRAP_DOMAIN_DEVELOPMENT'] %>
    port: <%= ENV['MAILTRAP_PORT_DEVELOPMENT'] %>
    username: <%= ENV['MAILTRAP_USERNAME_DEVELOPMENT'] %>
    password: <%= ENV['MAILTRAP_PASSWORD_DEVELOPMENT'] %>

production:
  mail:
    address: <%= ENV['MAILTRAP_ADDRESS_PRODUCTION'] %>
    domain: <%= ENV['MAILTRAP_DOMAIN_PRODUCTION'] %>
    port: <%= ENV['MAILTRAP_PORT_PRODUCTION'] %>
    username: <%= ENV['MAILTRAP_USERNAME_PRODUCTION'] %>
    password: <%= ENV['MAILTRAP_PASSWORD_PRODUCTION'] %>
