development:
  mail:
    address: <%= ENV['MAILTRAP_ADDRESS'] %>
    domain: <%= ENV['MAILTRAP_DOMAIN'] %>
    port: <%= ENV['MAILTRAP_PORT'] %>
    username: <%= ENV['MAILTRAP_USERNAME'] %>
    password: <%= ENV['MAILTRAP_PASSWORD'] %>
